loki:
  auth_enabled: false
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi

  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 2h

  service:
    type: NodePort
    nodePort: 31000
    port: 3100

loki-stack:
  loki:
    service:
      type: NodePort
      nodePort: 31000
      port: 3100

promtail:
  enabled: true
  config:
    scrape_configs:
      - job_name: kubernetes-pods-all
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: .*
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: .*
